import type { TemplateDownloadConfig } from "./template-download-form";

export const templateConfigs: Record<string, TemplateDownloadConfig> = {
  "roofing-estimate": {
    slug: "roofing-estimate",
    title: "Roofing Estimate",
    companyName: "Summit Roofing Co.",
    companyTagline: "Licensed & Insured | Residential & Commercial",
    documentNumber: "EST-R-2041",
    clientName: "Mark & Lisa Thompson",
    clientAddress: "742 Oakwood Dr, Austin, TX 78704",
    jobDescription: "Full roof replacement — 2,200 sq ft, single story ranch",
    lineItems: [
      { description: "Tear off existing asphalt shingles (2,200 sq ft)", amount: "$2,750" },
      { description: "GAF Timberline HDZ architectural shingles — installed", amount: "$9,900" },
      { description: "Synthetic underlayment + ice & water shield", amount: "$1,650" },
      { description: "Replace damaged decking (est. 200 sq ft plywood)", amount: "$800" },
      { description: "New drip edge, flashing, and ridge vent", amount: "$950" },
      { description: "Dumpster and debris removal", amount: "$450" },
      { description: "Building permit", amount: "$350" },
    ],
    subtotal: "$16,850",
    tax: "$1,348",
    total: "$18,198",
    notes: "Payment terms: 30% deposit at signing, 40% at materials delivery, 30% on completion. Price includes manufacturer 50-year limited lifetime warranty and 10-year workmanship warranty. Does not include interior damage repair, gutter replacement, or solar panel removal/reinstallation.",
    validityDays: 30,
  },

  "hvac-estimate": {
    slug: "hvac-estimate",
    title: "HVAC Estimate",
    companyName: "Comfort Air Solutions",
    companyTagline: "NATE-Certified Technicians | 24/7 Emergency Service",
    documentNumber: "EST-H-3087",
    clientName: "Jennifer Wu",
    clientAddress: "1205 Maple Ave, Denver, CO 80220",
    jobDescription: "Central AC replacement — 3-ton unit, 1,800 sq ft home",
    lineItems: [
      { description: "Carrier 24ACC636 — 3-ton 16 SEER2 condenser", amount: "$3,200" },
      { description: "Carrier FV4CNF003 evaporator coil", amount: "$850" },
      { description: "Copper line set + refrigerant charge (R-410A)", amount: "$475" },
      { description: "New thermostat (Honeywell T6 Pro programmable)", amount: "$185" },
      { description: "Electrical disconnect + whip upgrade", amount: "$250" },
      { description: "Labor — removal of old unit + full installation", amount: "$2,400" },
      { description: "Permit + inspection fee", amount: "$175" },
    ],
    subtotal: "$7,535",
    tax: "$603",
    total: "$8,138",
    notes: "Payment: 50% deposit, 50% on completion. Includes 10-year manufacturer parts warranty and 2-year labor warranty. Filter replacement and first-year maintenance check included. Does not include ductwork modification or attic insulation.",
    validityDays: 30,
  },

  "plumbing-estimate": {
    slug: "plumbing-estimate",
    title: "Plumbing Estimate",
    companyName: "Reliable Plumbing Pros",
    companyTagline: "Licensed Master Plumber | Same-Day Service",
    documentNumber: "EST-P-1156",
    clientName: "David & Sarah Martinez",
    clientAddress: "890 Cedar Lane, Phoenix, AZ 85004",
    jobDescription: "Bathroom remodel plumbing — master bath, relocate fixtures",
    lineItems: [
      { description: "Rough-in plumbing — new shower valve + supply lines", amount: "$1,200" },
      { description: "Relocate toilet drain (3 ft offset)", amount: "$650" },
      { description: "Install double vanity — hot/cold supply + drain", amount: "$475" },
      { description: "New shower pan drain + P-trap", amount: "$325" },
      { description: "Water heater connection upgrade (3/4\" PEX)", amount: "$280" },
      { description: "Materials — PEX, fittings, valves, cement", amount: "$350" },
      { description: "Permit + inspection", amount: "$125" },
    ],
    subtotal: "$3,405",
    tax: "$272",
    total: "$3,677",
    notes: "Payment: 40% deposit, 60% on completion. Includes 1-year workmanship warranty on all connections. Fixture installation is included; fixtures themselves are client-supplied. Does not include tile work, drywall patching, or painting.",
    validityDays: 30,
  },

  "electrical-estimate": {
    slug: "electrical-estimate",
    title: "Electrical Estimate",
    companyName: "Bright Spark Electrical",
    companyTagline: "Licensed Electrician | Residential & Commercial",
    documentNumber: "EST-E-4421",
    clientName: "Robert Chen",
    clientAddress: "3456 Elm St, Nashville, TN 37209",
    jobDescription: "Panel upgrade 100A to 200A + EV charger installation",
    lineItems: [
      { description: "200A main breaker panel (Square D Homeline)", amount: "$850" },
      { description: "Meter base upgrade + utility coordination", amount: "$475" },
      { description: "Transfer existing circuits to new panel", amount: "$1,200" },
      { description: "New 50A circuit for EV charger (40 ft run)", amount: "$680" },
      { description: "EV charger installation (client-supplied unit)", amount: "$350" },
      { description: "Grounding electrode upgrade to code", amount: "$225" },
      { description: "Permit + 2 inspections", amount: "$200" },
    ],
    subtotal: "$3,980",
    tax: "$318",
    total: "$4,298",
    notes: "Payment: 50% deposit, 50% on completion. All work to NEC 2023 code. Includes 2-year workmanship warranty. Utility company may require separate meter base purchase — will confirm before work begins. Does not include drywall repair if access cuts are needed.",
    validityDays: 30,
  },

  "handyman-invoice": {
    slug: "handyman-invoice",
    title: "Handyman Invoice",
    companyName: "Fix-It Frank Handyman",
    companyTagline: "Honest Work, Fair Prices | No Job Too Small",
    documentNumber: "INV-HM-0587",
    clientName: "Amanda Torres",
    clientAddress: "215 Birch Rd, Portland, OR 97201",
    jobDescription: "Miscellaneous home repairs — half-day service",
    lineItems: [
      { description: "Fix running toilet — replaced flapper + fill valve", amount: "$85" },
      { description: "Patch and paint drywall hole (6\" diameter)", amount: "$120" },
      { description: "Replace 3 light switches with dimmers", amount: "$135" },
      { description: "Recaulk master bathtub surround", amount: "$75" },
      { description: "Tighten loose deck railing + replace 2 balusters", amount: "$110" },
      { description: "Materials (hardware, caulk, paint)", amount: "$45" },
    ],
    subtotal: "$570",
    tax: "$46",
    total: "$616",
    notes: "4-hour minimum for half-day service. Materials billed at cost. Payment due on completion. Warranty: 90 days on all workmanship. Thank you for your business!",
  },

  "cleaning-invoice": {
    slug: "cleaning-invoice",
    title: "Cleaning Invoice",
    companyName: "Spotless Pro Cleaning",
    companyTagline: "Bonded & Insured | Eco-Friendly Products",
    documentNumber: "INV-CL-2294",
    clientName: "Karen Phillips",
    clientAddress: "1830 Pine St, Unit 4B, Chicago, IL 60614",
    jobDescription: "Move-out deep clean — 2BR/2BA apartment, 1,100 sq ft",
    lineItems: [
      { description: "Kitchen deep clean — appliances, cabinets, counters", amount: "$175" },
      { description: "Bathroom 1 — scrub, sanitize, grout cleaning", amount: "$120" },
      { description: "Bathroom 2 — scrub, sanitize, grout cleaning", amount: "$120" },
      { description: "Bedroom 1 — dust, vacuum, closet wipe-down", amount: "$75" },
      { description: "Bedroom 2 — dust, vacuum, closet wipe-down", amount: "$75" },
      { description: "Living area + hallway — dust, mop, baseboards", amount: "$95" },
      { description: "Windows interior (12 windows)", amount: "$60" },
    ],
    subtotal: "$720",
    tax: "$58",
    total: "$778",
    notes: "Move-out clean guarantee: if landlord flags any cleaning issue within 48 hours, we return at no charge. Payment due on completion. Cleaning supplies included in price.",
  },

  "landscaping-estimate": {
    slug: "landscaping-estimate",
    title: "Landscaping Estimate",
    companyName: "Green Valley Landscaping",
    companyTagline: "Design · Install · Maintain",
    documentNumber: "EST-LS-0934",
    clientName: "Tom & Emily Baker",
    clientAddress: "4500 Willow Creek Dr, Raleigh, NC 27603",
    jobDescription: "Front yard redesign — drought-tolerant landscape, 800 sq ft",
    lineItems: [
      { description: "Remove existing turf + disposal (800 sq ft)", amount: "$640" },
      { description: "Grading + soil amendment (compost mix)", amount: "$480" },
      { description: "Drip irrigation system — 4 zones", amount: "$1,200" },
      { description: "Native plants + ornamental grasses (32 plants)", amount: "$960" },
      { description: "River rock + decomposed granite (6 cubic yds)", amount: "$720" },
      { description: "Landscape edging — steel (120 linear ft)", amount: "$360" },
      { description: "3\" mulch layer (4 cubic yds)", amount: "$280" },
    ],
    subtotal: "$4,640",
    tax: "$371",
    total: "$5,011",
    notes: "Payment: 40% deposit, 60% on completion. 1-year plant replacement warranty (with maintenance plan). Irrigation system includes 2-year parts warranty. Design fee waived with project approval. Does not include lighting, fencing, or hardscape.",
    validityDays: 30,
  },

  "painting-estimate": {
    slug: "painting-estimate",
    title: "Painting Estimate",
    companyName: "Pro Finish Painting",
    companyTagline: "Interior & Exterior | Color Consultation Included",
    documentNumber: "EST-PT-1782",
    clientName: "Michael & Jessica Reed",
    clientAddress: "567 Sunset Blvd, San Diego, CA 92101",
    jobDescription: "Exterior repaint — 2-story colonial, 2,400 sq ft",
    lineItems: [
      { description: "Pressure wash all exterior surfaces", amount: "$450" },
      { description: "Scrape, sand, and prime peeling areas", amount: "$1,200" },
      { description: "Caulk windows, doors, and trim joints", amount: "$380" },
      { description: "2 coats Sherwin-Williams Duration (body color)", amount: "$3,600" },
      { description: "Trim + shutters — 2 coats (accent color)", amount: "$1,100" },
      { description: "Front door — strip + 2 coats (highlight color)", amount: "$250" },
      { description: "Materials — paint, primer, caulk, tape", amount: "$820" },
    ],
    subtotal: "$7,800",
    tax: "$624",
    total: "$8,424",
    notes: "Payment: 30% deposit, 40% at body coat completion, 30% on final walkthrough. Includes 5-year warranty against peeling, blistering, or fading (excludes acts of nature). Does not include stucco repair, wood rot replacement, or gutter painting. Rain delay: schedule extends without penalty.",
    validityDays: 30,
  },

  "construction-invoice": {
    slug: "construction-invoice",
    title: "Construction Invoice",
    companyName: "Granite Peak Builders",
    companyTagline: "General Contractor | Licensed & Bonded",
    documentNumber: "INV-GC-5503",
    clientName: "Andrew & Patricia Hall",
    clientAddress: "1290 Heritage Way, Salt Lake City, UT 84101",
    jobDescription: "Kitchen remodel — Phase 2 progress billing",
    lineItems: [
      { description: "Demolition + haul away (completed)", amount: "$2,800" },
      { description: "Rough plumbing — relocated sink + dishwasher", amount: "$1,950" },
      { description: "Electrical — new 20A circuits, under-cabinet LED", amount: "$2,100" },
      { description: "Framing — island + soffit modification", amount: "$1,400" },
      { description: "Drywall + mudding (kitchen + pantry)", amount: "$1,650" },
      { description: "Materials this phase (lumber, wire, pipe)", amount: "$1,100" },
    ],
    subtotal: "$11,000",
    tax: "$880",
    total: "$11,880",
    notes: "Phase 2 of 4. Total contract: $48,500. Paid to date: $14,550 (Phase 1). This invoice covers rough-in work. Next phase: cabinets, countertops, and tile. Change order #1 (add pot filler) approved — $320 added to Phase 3.",
  },

  "electrician-invoice": {
    slug: "electrician-invoice",
    title: "Electrician Invoice",
    companyName: "Bright Spark Electrical",
    companyTagline: "Licensed Electrician | Residential & Commercial",
    documentNumber: "INV-EL-3318",
    clientName: "Stephanie Morgan",
    clientAddress: "890 Oak Park Ave, Minneapolis, MN 55403",
    jobDescription: "Whole-house rewire — completed",
    lineItems: [
      { description: "Remove knob-and-tube wiring throughout", amount: "$2,400" },
      { description: "Install new 200A panel + breakers", amount: "$1,800" },
      { description: "Run new Romex circuits — 22 circuits total", amount: "$4,400" },
      { description: "Install outlets, switches, plates (64 devices)", amount: "$1,280" },
      { description: "Smoke/CO detectors — hardwired, 8 units", amount: "$640" },
      { description: "GFCI outlets — kitchen, bath, garage, exterior", amount: "$360" },
      { description: "Permit + 3 inspections", amount: "$350" },
    ],
    subtotal: "$11,230",
    tax: "$898",
    total: "$12,128",
    notes: "Final invoice. Balance due: $6,064 (50% deposit of $6,064 received). All work to NEC 2023 code. 3-year workmanship warranty. Certificate of compliance filed with city.",
  },

  "plumbing-invoice": {
    slug: "plumbing-invoice",
    title: "Plumbing Invoice",
    companyName: "Reliable Plumbing Pros",
    companyTagline: "Licensed Master Plumber | Same-Day Service",
    documentNumber: "INV-PL-2089",
    clientName: "Chris & Laura Kim",
    clientAddress: "2105 Magnolia Ct, Tampa, FL 33602",
    jobDescription: "Emergency water heater replacement",
    lineItems: [
      { description: "Remove failed 40-gal gas water heater", amount: "$200" },
      { description: "Rheem 50-gal gas water heater (unit + delivery)", amount: "$1,150" },
      { description: "New water connections + gas flex line", amount: "$275" },
      { description: "Expansion tank installation", amount: "$185" },
      { description: "New earthquake straps + drip pan", amount: "$95" },
      { description: "Emergency same-day service fee", amount: "$150" },
    ],
    subtotal: "$2,055",
    tax: "$164",
    total: "$2,219",
    notes: "Payment due on completion. Rheem 6-year tank warranty + 1-year labor warranty. Old unit hauled away at no charge. Tank passed city inspection — permit included in price.",
  },

  "pressure-washing-estimate": {
    slug: "pressure-washing-estimate",
    title: "Pressure Washing Estimate",
    companyName: "Clean Blast Exterior",
    companyTagline: "Soft Wash & Pressure Wash Specialists",
    documentNumber: "EST-PW-0762",
    clientName: "Brian & Donna Williams",
    clientAddress: "3350 Laurel Hill Dr, Atlanta, GA 30305",
    jobDescription: "Full exterior wash — house, driveway, patio, fence",
    lineItems: [
      { description: "House siding soft wash — 2,600 sq ft", amount: "$390" },
      { description: "Driveway pressure wash — 800 sq ft concrete", amount: "$200" },
      { description: "Patio + walkway — 400 sq ft flagstone", amount: "$120" },
      { description: "Wood fence — soft wash both sides (120 linear ft)", amount: "$240" },
      { description: "Gutter face cleaning (exterior only)", amount: "$90" },
      { description: "Pre-treatment (mold/mildew/algae solution)", amount: "$60" },
    ],
    subtotal: "$1,100",
    tax: "$88",
    total: "$1,188",
    notes: "Payment due on completion. Soft wash method used on all painted/stained surfaces to prevent damage. We protect all plants and cover outdoor furniture. No water enters the home. Satisfaction guaranteed — we re-clean any area you're not happy with.",
    validityDays: 14,
  },

  "general-contractor-estimate": {
    slug: "general-contractor-estimate",
    title: "General Contractor Estimate",
    companyName: "Granite Peak Builders",
    companyTagline: "General Contractor | Licensed & Bonded",
    documentNumber: "EST-GC-2210",
    clientName: "James & Nicole Foster",
    clientAddress: "1780 Fieldstone Ln, Charlotte, NC 28205",
    jobDescription: "Basement finish — 600 sq ft, 1 bedroom + bathroom",
    lineItems: [
      { description: "Framing — walls, door openings, ceiling soffits", amount: "$3,200" },
      { description: "Electrical — 6 circuits, outlets, lighting", amount: "$2,800" },
      { description: "Plumbing — bathroom rough-in + finish", amount: "$3,500" },
      { description: "HVAC — extend ductwork + 2 supply registers", amount: "$1,600" },
      { description: "Insulation + vapor barrier", amount: "$1,200" },
      { description: "Drywall + finish (walls + ceiling)", amount: "$2,400" },
      { description: "Flooring — luxury vinyl plank (600 sq ft)", amount: "$3,000" },
      { description: "Trim, doors, paint", amount: "$1,800" },
      { description: "Permits + inspections", amount: "$500" },
    ],
    subtotal: "$20,000",
    tax: "$1,600",
    total: "$21,600",
    notes: "Payment: 20% at signing, 30% at framing inspection, 30% at drywall completion, 20% on final walkthrough. Timeline: 6–8 weeks. GC markup included. Subcontractors are licensed and insured. Does not include egress window (add $2,500–$4,000 if required by code).",
    validityDays: 30,
  },

  "auto-body-repair-invoice": {
    slug: "auto-body-repair-invoice",
    title: "Auto Body Repair Invoice",
    companyName: "Precision Auto Body",
    companyTagline: "I-CAR Gold Certified | All Insurance Accepted",
    documentNumber: "INV-AB-4471",
    clientName: "Rachel Adams",
    clientAddress: "555 Commerce Pkwy, Houston, TX 77002",
    jobDescription: "Front-end collision repair — 2022 Honda Accord",
    lineItems: [
      { description: "Front bumper cover — remove, repair, refinish", amount: "$680" },
      { description: "Hood — remove dents, prime, basecoat/clearcoat", amount: "$1,100" },
      { description: "Right fender — pull, fill, block, refinish", amount: "$850" },
      { description: "Headlight assembly (RH) — replace OEM", amount: "$420" },
      { description: "Blend right door for color match", amount: "$350" },
      { description: "Parts — clips, brackets, moldings", amount: "$185" },
      { description: "Paint materials — primer, base, clear, tint", amount: "$310" },
    ],
    subtotal: "$3,895",
    tax: "$312",
    total: "$4,207",
    notes: "Insurance claim #CLM-88721. Deductible: $500 (customer responsibility). Supplement submitted for hidden damage behind bumper — pending adjuster approval ($600 est.). Lifetime warranty on all paint and body work.",
  },

  "independent-contractor-invoice": {
    slug: "independent-contractor-invoice",
    title: "Independent Contractor Invoice",
    companyName: "Alex Rivera Consulting",
    companyTagline: "Web Development & Technical Consulting",
    documentNumber: "INV-IC-0143",
    clientName: "Orion Digital Agency",
    clientAddress: "200 W Adams St, Suite 1400, Chicago, IL 60606",
    jobDescription: "Website redesign project — March 2026 billing",
    lineItems: [
      { description: "UI/UX design — homepage + 4 interior pages (16 hrs)", amount: "$2,400" },
      { description: "Front-end development — React components (24 hrs)", amount: "$3,600" },
      { description: "CMS integration — headless WordPress setup (8 hrs)", amount: "$1,200" },
      { description: "Performance optimization + accessibility audit (4 hrs)", amount: "$600" },
      { description: "QA testing + bug fixes (6 hrs)", amount: "$900" },
    ],
    subtotal: "$8,700",
    tax: "$0",
    total: "$8,700",
    notes: "Net 30 payment terms. Rate: $150/hr. No sales tax — services between businesses. W-9 on file. Time tracked in Toggl — detailed report available on request. Next milestone: content migration (est. 12 hrs).",
  },

  "lawn-care-invoice": {
    slug: "lawn-care-invoice",
    title: "Lawn Care Invoice",
    companyName: "Green Edge Lawn Care",
    companyTagline: "Weekly Maintenance · Seasonal Treatments · Free Estimates",
    documentNumber: "INV-LC-1847",
    clientName: "Paul & Maria Gonzalez",
    clientAddress: "4210 Sunset Ridge, Orlando, FL 32801",
    jobDescription: "March 2026 — monthly lawn maintenance",
    lineItems: [
      { description: "Weekly mowing + edging (4 visits)", amount: "$180" },
      { description: "String trimming — fence line + beds", amount: "$60" },
      { description: "Blow off driveway, walkways, patio", amount: "$40" },
      { description: "Spring fertilization (16-4-8, 10,000 sq ft)", amount: "$85" },
      { description: "Pre-emergent weed control application", amount: "$75" },
      { description: "Shrub trimming — front beds (quarterly)", amount: "$120" },
    ],
    subtotal: "$560",
    tax: "$45",
    total: "$605",
    notes: "Monthly billing — due within 15 days. Service every Thursday (weather permitting, makeup day = Friday). Annual contract discount: 10% off monthly rate. Includes all equipment, fuel, and materials. Does not include irrigation repair, tree trimming, or mulch installation.",
  },

  "tree-service-invoice": {
    slug: "tree-service-invoice",
    title: "Tree Service Invoice",
    companyName: "Premier Tree Services",
    companyTagline: "ISA-Certified Arborist · Licensed & Insured · Emergency Service",
    documentNumber: "INV-TS-3429",
    clientName: "Jennifer Martinez",
    clientAddress: "847 Oak Ridge Road, Portland, OR 97214",
    jobDescription: "Remove 40ft oak tree, grind stump, remove debris",
    lineItems: [
      { description: "Tree removal — 40ft oak, bucket truck", amount: "$1,200" },
      { description: "Stump grinding — 24in diameter, 18in deep", amount: "$350" },
      { description: "Debris hauling — 12 cu yd chipper truck", amount: "$400" },
      { description: "Site cleanup and mulching", amount: "$150" },
    ],
    subtotal: "$2,100",
    tax: "$168",
    total: "$2,268",
    notes: "Payment: 50% deposit ($1,134) upon agreement, 50% ($1,134) due upon completion. Includes all equipment, crew, and debris removal. Does not include new plantings or ground-level stump removal. Work performed weather-permitting; rain delays do not extend the job timeline beyond the original estimate date.",
  },
};
